name: Build Buildroot OS Image

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Clone Luckfox SDK repository
        run: |
          git clone https://github.com/LuckfoxTECH/luckfox-pico.git --depth=1 $HOME/luckfox-pico

      - name: Clone SeedSigner repository
        run: |
          git clone https://github.com/SeedSigner/seedsigner.git --depth=1 $HOME/seedsigner

      - name: Clone SeedSigner OS repository
        run: |
          git clone https://github.com/SeedSigner/seedsigner-os.git --depth=1 $HOME/seedsigner-os

      - name: Build Docker image
        run: |
          cd $GITHUB_WORKSPACE/buildroot
          docker build -t foxbuilder:latest .

      # - name: Build OS image
      #   run: |
      #     LUCKFOX_SDK_DIR=$HOME/luckfox-pico
      #     SEEDSIGNER_CODE_DIR=$HOME/seedsigner
      #     LUCKFOX_BOARD_CFG_DIR=$GITHUB_WORKSPACE
      #     SEEDSIGNER_OS_DIR=$HOME/seedsigner-os
          
      #     docker run --name luckfox-builder \
      #       -v $LUCKFOX_SDK_DIR:/mnt/host \
      #       -v $SEEDSIGNER_CODE_DIR:/mnt/ss \
      #       -v $LUCKFOX_BOARD_CFG_DIR:/mnt/cfg \
      #       -v $SEEDSIGNER_OS_DIR:/mnt/ssos \
      #       foxbuilder:latest \
      #       /bin/bash -c "cd /mnt/host && \
      #       cp /mnt/cfg/buildroot/configs/config_20241218184332.config sysdrv/source/buildroot/buildroot-2023.02.6/.config && \
      #       ./build.sh uboot && \
      #       ./build.sh kernel && \
      #       ./build.sh rootfs && \
      #       ./build.sh media && \
      #       cp /mnt/cfg/config/luckfox.cfg /mnt/host/output/out/rootfs_uclibc_rv1106/etc/luckfox.cfg && \
      #       cp -r /mnt/ss/src/ /mnt/host/output/out/rootfs_uclibc_rv1106/seedsigner && \
      #       ./build.sh firmware && \
      #       cd /mnt/host/output/image && \
      #       /mnt/cfg/buildroot/blkenvflash seedsigner-luckfox-pico.img"

      # - name: Upload OS image
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: seedsigner-luckfox-pico-image
      #     path: ${{ env.HOME }}/luckfox-pico/output/image/seedsigner-luckfox-pico.img